version: "3.2"

services:
  housing-finance-interim-api:
    image: housing-finance-interim-api
    build:
      context: .
      dockerfile: HousingFinanceInterimApi/Dockerfile
      args:
      - LBHPACKAGESTOKEN=${LBHPACKAGESTOKEN}
    network_mode: "host"
    environment:
      - CONNECTION_STRING=${CONNECTION_STRING}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - WAIT_DURATION=${WAIT_DURATION}
      - BATCH_SIZE=${BATCH_SIZE}
      - CASH_FILE_REGEX=${CASH_FILE_REGEX}
      - HOUSING_FILE_REGEX=${HOUSING_FILE_REGEX}
      - ACCEPTED_ORIGINS=${ACCEPTED_ORIGINS}
      - CHARGES_BATCH_YEARS=${CHARGES_BATCH_YEARS}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - S3_OBJECT_PREFIX=${S3_OBJECT_PREFIX}
      - HOUSING_FINANCE_ALLOWED_GROUPS=${HOUSING_FINANCE_ALLOWED_GROUPS}

#    Dev database not working
#    links:
#      - dev-database

  dev-database:
    env_file:
      - database.env
    image: mcr.microsoft.com/mssql/server:2019-latest
    volumes:
      - ./database:/docker-entrypoint-initdb.d

  housing-finance-interim-api-test:
    image: housing-finance-interim-api-test
    build:
      context: .
      dockerfile: HousingFinanceInterimApi.Tests/Dockerfile
      args:
      - LBHPACKAGESTOKEN=${LBHPACKAGESTOKEN}
    environment:
      - DB_SERVER=test-database
      - DB_USERNAME=myuser
      - DB_PASSWORD=mypassword
      - DB_DATABASE=testdb
    links:
      - test-database

  test-database:
    image: test-database
    build:
      context: .
      dockerfile: database/Dockerfile
    ports:
      - 1433:1433
    env_file:
      - database.env
