INSERT INTO sow2b.dbo.uhrentgroup (rentgrp_ref, rentgrp_desc, prd_code, rg_period_no, rg_year, no_of_periods, rentgrp_sid, spreadsheet_tab_name) VALUES (N'GPS', N'Gar & Park HRA  ', N'WK', 27, 2021, 52, 0, N'GarParkHRA');
INSERT INTO sow2b.dbo.uhrentgroup (rentgrp_ref, rentgrp_desc, prd_code, rg_period_no, rg_year, no_of_periods, rentgrp_sid, spreadsheet_tab_name) VALUES (N'HGF', N'Housing Gen Fund', N'WK', 27, 2021, 52, 0, N'HousingGenFund');
INSERT INTO sow2b.dbo.uhrentgroup (rentgrp_ref, rentgrp_desc, prd_code, rg_period_no, rg_year, no_of_periods, rentgrp_sid, spreadsheet_tab_name) VALUES (N'HRA', N'Housing Revenue ', N'WK', 27, 2021, 52, 0, N'HousingRevenue');
INSERT INTO sow2b.dbo.uhrentgroup (rentgrp_ref, rentgrp_desc, prd_code, rg_period_no, rg_year, no_of_periods, rentgrp_sid, spreadsheet_tab_name) VALUES (N'LMW', N'LH Major Works  ', N'01', 7, 2021, 12, 0, N'LHMajorWorks');
INSERT INTO sow2b.dbo.uhrentgroup (rentgrp_ref, rentgrp_desc, prd_code, rg_period_no, rg_year, no_of_periods, rentgrp_sid, spreadsheet_tab_name) VALUES (N'LSC', N'LH Serv Charges ', N'01', 7, 2021, 12, 0, N'LHServCharges');
INSERT INTO sow2b.dbo.uhrentgroup (rentgrp_ref, rentgrp_desc, prd_code, rg_period_no, rg_year, no_of_periods, rentgrp_sid, spreadsheet_tab_name) VALUES (N'RSL', N'RSL and XBorough', N'01', 12, 2012, 12, 0, null);
INSERT INTO sow2b.dbo.uhrentgroup (rentgrp_ref, rentgrp_desc, prd_code, rg_period_no, rg_year, no_of_periods, rentgrp_sid, spreadsheet_tab_name) VALUES (N'TAG', N'Temp Acc Gen Fun', N'WK', 27, 2021, 52, 0, N'TempAccGenFun');
INSERT INTO sow2b.dbo.uhrentgroup (rentgrp_ref, rentgrp_desc, prd_code, rg_period_no, rg_year, no_of_periods, rentgrp_sid, spreadsheet_tab_name) VALUES (N'TAH', N'Temp Accom HRA  ', N'WK', 27, 2021, 52, 0, N'TempAccomHRA');
INSERT INTO sow2b.dbo.uhrentgroup (rentgrp_ref, rentgrp_desc, prd_code, rg_period_no, rg_year, no_of_periods, rentgrp_sid, spreadsheet_tab_name) VALUES (N'TRA', N'Travel Gen Fund ', N'WK', 27, 2021, 52, 0, N'TravelGenFund');
